controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_produit_show:
    path: /produit/{slug}
    controller: App\Controller\ProduitController::show
    requirements:
        slug: '[^/]+'
